/*
A KBase module: kb_das_tool
*/

module kb_das_tool {

    /* A boolean - 0 for false, 1 for true.
        @range (0, 1)
    */
    typedef int boolean;

    /* An X/Y/Z style reference
    */
    typedef string obj_ref;

    /*
        required params:
        assembly_ref: Genome assembly object reference
        binned_contig_name: BinnedContig object name and output file header
        workspace_name: the name of the workspace it gets saved to.

        optional params:
        thread: number of threads; default 1
        min_contig_length: minimum contig length; default 1000
        contig_split_length: length to split long contigs; default 10000
        ref: https://github.com/cmks/DAS_Tool

    */
    typedef structure {
        obj_ref assembly_ref;
        string binned_contig_name;
        string workspace_name;
        list<obj_ref> reads_list;

        int thread;
        int min_contig_length;
        int contig_split_length;
    } DASToolInputParams;

    /*
        result_folder: folder path that holds all files generated by run_kb_das_tool
        report_name: report name generated by KBaseReport
        report_ref: report reference generated by KBaseReport
    */
    typedef structure{
        string result_directory;
        obj_ref binned_contig_obj_ref;
        string report_name;
        string report_ref;
    } DASToolResult;

    funcdef run_kb_das_tool(DASToolInputParams params)
        returns (DASToolResult returnVal) authentication required;

};
